### ISSUE TITLE
How to use the code

### ISSUE THREAD

**Issue by smilenew** [immuno121/ALS4GAN#2]
Hi! I am very interested in this project, can you update the description of the code as soon as possible. Thanks a lot.

**Comment by immuno121** [comment]
Yes, will do it soon. We are doing a bit of refactoring and testing the code. We will update the README as soon as that is done

**Comment by abhigoku10** [comment]
@immuno121  can you please let us knw ehen will u update how to use the code , this is really very good project

**Comment by immuno121** [comment]
README has been updated. Going to close this issue for now :)
Feel free to open another issue if you face any challenges running the code or have any other questions.
